### ISSUE TITLE
Encoding Problem 

### ISSUE THREAD

**Issue by Pinderb** [andreafrancia/trash-cli#119]
trash-put './older3/Users/Cynamon/Documents/Business/E-ZPassÂ® New York.html'
(where the characters after Pass are 302 and 256 octal)
fails with 
Traceback (most recent call last):
  File "/usr/bin/trash-put", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/trashcli/put.py", line 21, in main
    ).run(sys.argv)
  File "/usr/lib/python3.6/site-packages/trashcli/put.py", line 68, in run
    trashcan.trash_all(args)
  File "/usr/lib/python3.6/site-packages/trashcli/put.py", line 246, in trash_all
    self.trash(arg)
  File "/usr/lib/python3.6/site-packages/trashcli/put.py", line 280, in trash
    trashed_file = trash_dir.trash(file)
  File "/usr/lib/python3.6/site-packages/trashcli/put.py", line 399, in trash
    content = self.format_trashinfo(original_location, self.now())
  File "/usr/lib/python3.6/site-packages/trashcli/put.py", line 427, in format_trashinfo
    "Path=%s\n" % format_original_location(original_location) +
  File "/usr/lib/python3.6/site-packages/trashcli/put.py", line 425, in format_original_location
    return quote(original_location,'/')
  File "/usr/lib64/python3.6/urllib/parse.py", line 783, in quote
    string = string.encode(encoding, errors)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 75-76: surrogates not allowed

Fedora 27 bash
I tried
export PYTHONIOENCODING=ascii
and
export PYTHONIOENCODING=latin1
but they didn't make a difference

**Comment by xnuk** [comment]
I have same problem:
```sh
$ touch "$(printf '안녕하세요' | iconv -f utf-8 -t cp949).js"
$ trash-put *.js
```

Result:
```
Traceback (most recent call last):
  File "/usr/bin/trash-put", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/trashcli/put/main.py", line 34, in main
    return cmd.run(sys.argv, os.environ, os.getuid())
  File "/usr/lib/python3.10/site-packages/trashcli/put/trash_put_cmd.py", line 27, in run
    result = self.trash_all.trash_all(options.files,
  File "/usr/lib/python3.10/site-packages/trashcli/put/trash_all.py", line 26, in trash_all
    result = self.trasher.trash(arg,
  File "/usr/lib/python3.10/site-packages/trashcli/put/trasher.py", line 68, in trash
    return self.file_trasher.trash_file(path,
  File "/usr/lib/python3.10/site-packages/trashcli/put/file_trasher.py", line 50, in trash_file
    file_has_been_trashed = self.trash_file_in.trash_file_in(path,
  File "/usr/lib/python3.10/site-packages/trashcli/put/trash_file_in.py", line 62, in trash_file_in
    self.trash_dir.trash2(path, program_name, verbose,
  File "/usr/lib/python3.10/site-packages/trashcli/put/trash_directory_for_put.py", line 33, in trash2
    content = format_trashinfo(original_location, self.clock.now())
  File "/usr/lib/python3.10/site-packages/trashcli/put/trash_directory_for_put.py", line 50, in format_trashinfo
    "Path=%s\n" % format_original_location(original_location) +
  File "/usr/lib/python3.10/site-packages/trashcli/put/trash_directory_for_put.py", line 60, in format_original_location
    return url_quote(original_location, '/')
  File "/usr/lib/python3.10/urllib/parse.py", line 863, in quote
    string = string.encode(encoding, errors)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcbe' in position 24: surrogates not allowed
```

Hex representation of the filename:
```sh
$ printf '안녕하세요' | iconv -f utf-8 -t cp949 | hexdump -C
00000000  be c8 b3 e7 c7 cf bc bc  bf e4                    |..........|
0000000a
```
