### ISSUE TITLE
broken pipe traceback

### ISSUE THREAD

**Issue by faridcher** [andreafrancia/trash-cli#143]
I get this error when piping to `head` command:

```shell
# trash --version                                                                                                                                     
trash 0.17.1.14
# trash-list | head                                                                                                                                          
2019-05-02 15:51:40 /home/farid/feh_013203_000001_filelist
2019-05-02 15:51:40 /home/farid/feh_013203_000002_Screenshot from 2019-05-02 15-37-45.png
2019-05-02 22:57:28 /home/farid/.zplug/zcompdump
2019-05-03 16:54:44 /home/farid/Downloads/InRelease
2019-05-03 22:35:50 /home/farid/sources.list
2019-05-03 17:40:30 /home/farid/Pictures/Screenshot from 2019-05-02 16-16-24 - 1.png
2019-05-03 16:54:35 /home/farid/Downloads/Release
2019-05-02 15:51:40 /home/farid/feh_012612_000001_filelist
2019-05-03 16:54:35 /home/farid/Downloads/Release (1)
2019-05-03 17:40:30 /home/farid/Pictures/Screenshot from 2019-05-02 16-16-24.png
Traceback (most recent call last):
  File "/usr/local/bin/trash-list", line 5, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/trashcli/cmds.py", line 51, in list
    ).run(*sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/trashcli/list.py", line 37, in run
    parse(argv)
  File "/usr/local/lib/python2.7/dist-packages/trashcli/trash.py", line 110, in __call__
    self.default_action()
  File "/usr/local/lib/python2.7/dist-packages/trashcli/list.py", line 51, in list_trash
    trashdirs.list_trashdirs()
  File "/usr/local/lib/python2.7/dist-packages/trashcli/trash.py", line 151, in list_trashdirs
    self._for_each_volume_trashcan()
  File "/usr/local/lib/python2.7/dist-packages/trashcli/trash.py", line 158, in _for_each_volume_trashcan
    self.emit_trashcans_for(volume)
  File "/usr/local/lib/python2.7/dist-packages/trashcli/trash.py", line 160, in emit_trashcans_for
    self.emit_trashcan_1_for(volume)
  File "/usr/local/lib/python2.7/dist-packages/trashcli/trash.py", line 171, in emit_trashcan_1_for
    self.top_trashdir_rules.valid_to_be_read(top_trashdir_path, IsValidOutput())
  File "/usr/local/lib/python2.7/dist-packages/trashcli/trash.py", line 238, in valid_to_be_read
    output.is_valid()
  File "/usr/local/lib/python2.7/dist-packages/trashcli/trash.py", line 170, in is_valid
    self.on_trash_dir_found(top_trashdir_path, volume)
  File "/usr/local/lib/python2.7/dist-packages/trashcli/trash.py", line 189, in analize_trash_directory
    trashdir.each_trashinfo(self.on_trashinfo_found)
  File "/usr/local/lib/python2.7/dist-packages/trashcli/trash.py", line 267, in each_trashinfo
    action(os.path.join(self._info_dir(), entry))
  File "/usr/local/lib/python2.7/dist-packages/trashcli/list.py", line 64, in _print_trashinfo
    self.output.print_entry(deletion_date, path)
  File "/usr/local/lib/python2.7/dist-packages/trashcli/list.py", line 96, in print_entry
    self.println("%s %s" %(maybe_deletion_date, original_location))
  File "/usr/local/lib/python2.7/dist-packages/trashcli/list.py", line 78, in println
    self.out.write(line+'\n')
IOError: [Errno 32] Broken pipe
```

**Comment by andreafrancia** [comment]
Can't reproduce. Please try a newer version. Use pip as described in README.rst to know how to install it using pip.
