### ISSUE TITLE
ModuleNotFoundError: No module named 'psutil'

### ISSUE THREAD

**Issue by cfsanderson** [andreafrancia/trash-cli#183]
Seeing this when running any `trash` commands. Didn't see a related issue. I'm running Big Sur and Python 3.9.0. Things seem to work as normal.

```
Traceback (most recent call last):
  File "/usr/local/bin/trash-empty", line 5, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/trash-cli/0.20.11.23/libexec/lib/python3.9/site-packages/trashcli/empty.py", line 22, in main
    return EmptyCmd(
  File "/usr/local/Cellar/trash-cli/0.20.11.23/libexec/lib/python3.9/site-packages/trashcli/empty.py", line 69, in run
    parse(argv)
  File "/usr/local/Cellar/trash-cli/0.20.11.23/libexec/lib/python3.9/site-packages/trashcli/trash.py", line 110, in __call__
    self.default_action()
  File "/usr/local/Cellar/trash-cli/0.20.11.23/libexec/lib/python3.9/site-packages/trashcli/empty.py", line 104, in empty_all_trashdirs
    trashdirs.list_trashdirs()
  File "/usr/local/Cellar/trash-cli/0.20.11.23/libexec/lib/python3.9/site-packages/trashcli/trash.py", line 151, in list_trashdirs
    self._for_each_volume_trashcan()
  File "/usr/local/Cellar/trash-cli/0.20.11.23/libexec/lib/python3.9/site-packages/trashcli/trash.py", line 157, in _for_each_volume_trashcan
    for volume in self.mount_points():
  File "/usr/local/Cellar/trash-cli/0.20.11.23/libexec/lib/python3.9/site-packages/trashcli/list_mount_points.py", line 8, in mount_points
    import psutil
ModuleNotFoundError: No module named 'psutil'
```

**Comment by andreafrancia** [comment]
Try installing `psutil`:
```
pip3 install psutil
```

**Comment by cfsanderson** [comment]
> Try installing `psutil`:
> 
> ```
> pip3 install psutil
> ```

Thanks @andreafrancia. I tried that and the install looks successful but still getting the error. I'm seeing this same error on both my work and personal machines by the way. They are set up very similar so that may not help but thought I'd mention. I'm using [asdf version manager](https://github.com/asdf-vm/asdf) and I'm questioning whether or not that has something to do with it.

**Comment by andreafrancia** [comment]
Could you please share the command you used to  install trash-cli?

**Comment by cfsanderson** [comment]
I use homebrew so `brew install trash-cli`

**Comment by andreafrancia** [comment]
Try:
```
brew uninstall trash-cli
pip3 install trash-cli
```

**Comment by cfsanderson** [comment]
That worked, thank you! 
It didn't at first, but does after `asdf reshim`.
