### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/proc/filesystems'

### ISSUE THREAD

**Issue by babaric-dev** [andreafrancia/trash-cli#283]
When I use `trash-empty` or `trash-rm`, this error appears:
```
Traceback (most recent call last):
  File "/usr/local/bin/trash-rm", line 5, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/trashcli/rm.py", line 102, in main
    cmd.run(sys.argv, os.getuid())
  File "/usr/local/lib/python3.10/dist-packages/trashcli/rm.py", line 69, in run
    for event, args in scanner.scan_trash_dirs(self.environ, uid):
  File "/usr/local/lib/python3.10/dist-packages/trashcli/trash_dirs_scanner.py", line 82, in scan_trash_dirs
    for volume in self.volumes_listing.list_volumes(environ):
  File "/usr/local/lib/python3.10/dist-packages/trashcli/list_mount_points.py", line 18, in os_mount_points
    fstypes += set([p.fstype for p in psutil.disk_partitions()])
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 2021, in disk_partitions
    ret = _psplatform.disk_partitions(all)
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1275, in disk_partitions
    with open_text("%s/filesystems" % procfs_path) as f:
  File "/usr/lib/python3/dist-packages/psutil/_common.py", line 725, in open_text
    return open(fname, "rt", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/filesystems'
```
even when files are successfully removed

**Comment by andreafrancia** [comment]
There is something unexpected in your system configuration.

Please try also these commands and share the output:
 - ls -lad /proc/filesystem
 - cat /proc/filesystem
 - trash-list --volumes
 - trash-list --debug-volumes

**Comment by babaric-dev** [comment]
It seems to be an issue of psutil. I reported it and they already fixed it.

**Comment by babaric-dev** [comment]
Inside `list_mount_points.py`, adding `all=True` when calling `psutil.disk_partitions` will fix the issue. Are there any side effects? If not, please use my suggestion.

**Comment by andreafrancia** [comment]
I used all=True

**Comment by andreafrancia** [comment]
@mizzunet please report a proper bug report opening a new issue, following the instruction and providigin all the relevant information.
