### ISSUE TITLE
Crash with `--volumes`: AttributeError: 'PrintVolumesList' object has no attribute 'run_action'

### ISSUE THREAD

**Issue by alichtman** [andreafrancia/trash-cli#334]
Crash when using `--volumes`.

```
shotwell on  master is 📦 v33.alpha via 💎 v3.2.2 took 40ms
12:10:36 PM ➜ trash-list --volumes
Traceback (most recent call last):
  File "/usr/local/bin/trash-list", line 5, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/alichtman/.local/pipx/venvs/trash-cli/lib/python3.11/site-packages/trashcli/list/main.py", line 41, in main
    ).run(sys.argv)
      ^^^^^^^^^^^^^
  File "/home/alichtman/.local/pipx/venvs/trash-cli/lib/python3.11/site-packages/trashcli/list/main.py", line 91, in run
    action.run_action(args)
    ^^^^^^^^^^^^^^^^^
AttributeError: 'PrintVolumesList' object has no attribute 'run_action'
```

**trash-cli version**
trash-list 0.23.11.10

**Are you using the latest version of trash-cli?**
Yes

**Have you tried if the bug is present in the latest version of trash-cli?**
Yes

**Operating system:**
 - OS: Ubuntu 23.10 (mantic) x86_64

**To Reproduce**
Copy and paste the commands (and their output) to execute in order to reproduce 
the behavior:

$ trash-list --volumes

**Expected behavior**

Not a crash.

**Comment by andreafrancia** [comment]
Thank you, solved.
