### ISSUE TITLE
Permission denied: '/proc/filesystems' on Termux

### ISSUE THREAD

**Issue by mizzunet** [andreafrancia/trash-cli#348]
**Describe the bug**
`trash-empty` fails to run with following on Termux(Android 14)
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/trash-empty", line 5, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/trashcli/empty/main.py", line 35, in main
    return empty_cmd.run_cmd(sys.argv[1:], os.environ, os.getuid())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/trashcli/empty/empty_cmd.py", line 75, in run_cmd
    return self.empty_action.run_action(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/trashcli/empty/empty_action.py", line 68, in run_action
    delete_pass = self.guard.ask_the_user(args.interactive,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/trashcli/empty/guard.py", line 21, in ask_the_user
    return self._interactive(trash_dirs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/trashcli/empty/guard.py", line 27, in _interactive
    trash_dirs_list = list(trash_dirs)  # type: Iterable[TrashDir]
                      ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/trashcli/list/trash_dir_selector.py", line 33, in select
    for dir in self.current_user_dirs.scan_trash_dirs(environ, uid):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/trashcli/trash_dirs_scanner.py", line 81, in scan_trash_dirs
    for volume in self.volumes_listing.list_volumes(environ):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/trashcli/fstab/mount_points_listing.py", line 47, in os_mount_points
    fstypes += set([p.fstype for p in psutil.disk_partitions()])
                                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/__init__.py", line 2052, in disk_partitions
    return _psplatform.disk_partitions(all)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_pslinux.py", line 1338, in disk_partitions
    with open_text("%s/filesystems" % procfs_path) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_common.py", line 813, in open_text
    fobj = open(
           ^^^^^
PermissionError: [Errno 13] Permission denied: '/proc/filesystems'
```

**trash-cli version**
0.24.5.26

**Are you using the latest version of trash-cli?**
Yes

**Operating system:**
 - OS: Android 14
 - 
**To Reproduce**
Copy and paste the commands (and their output) to execute in order to reproduce 
the behavior:

$ trash-empty

**Expected behavior**
Run command and empty trays directory

**Volumes detail**
Seems trash-list --debug-volumes too has the same error
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/trash-list", line 5, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/trashcli/list/main.py", line 41, in main
    ).run(sys.argv)
      ^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/trashcli/list/main.py", line 92, in run
    action.run_action(args)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/trashcli/list/minor_actions/debug_volumes.py", line 16, in run_action
    physical = sorted([p for p in psutil.disk_partitions()],
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/__init__.py", line 2052, in disk_partitions
    return _psplatform.disk_partitions(all)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_pslinux.py", line 1338, in disk_partitions
    with open_text("%s/filesystems" % procfs_path) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_common.py", line 813, in open_text
    fobj = open(
           ^^^^^
PermissionError: [Errno 13] Permission denied: '/proc/filesystems'
```

**Comment by andreafrancia** [comment]
This seem be caused by this issue of psutil https://github.com/giampaolo/psutil/issues/2191

I need help for this problem from someone that has access to an Termux PRoot Ubuntu installation and knows how it work.

A possible workaround is to add a flag in trash-empty to disable the search of partitions:
```bash
$ trash-empty --current-volume-only
```

@mizzunet Thank you for your detailed submission!
@mizzunet can you please send me the output of the command "df" on your Termux system?

**Comment by andreafrancia** [comment]
@mizzunet 
The workaround I mentioned earlier is something I think we need to have in trash-cli to workaround the problem in psutils under Termux. Sorry if weren't clear.

The option `--current-volume-only` yet is not available in your trash-cli installation because I started working on after I sent my last message. 

I have finished it yet but during the working I discovered a possible temporary solution for you.

Try to prepend this the setting of the variable TRASH_VOLUMES before launching the trash-empty command.
```
$ TRASH_VOLUMES=$PWD trash-empty
```

It should at least empty the trash directory in the current volume.
The TRASH_VOLUMES variable works with trash-empy, trash-rm, and trash-list.

Please let me know if it works and also please send me the output of the following command  on Termux 
```
$ uname -a
```

So I can add a warning in trash-cli when it detects that is running under Termux if problems arises when searching for volumes.

**Comment by jvschiavo** [comment]
Is there a way to make it display the trash-dirs in Termux? (the `trash-list --trash-dirs` command also doesn't work at the moment)

**Comment by Holton181** [comment]
Yes, --trash-dirs do work with above mentioned workaround, prepend with TRASH_VOLUMES=$PWD, i.e.:

TRASH_VOLUMES=$PWD trash-list --trash-dirs


Unfortunately, it works for everything except for trash-restore.

For everything else, create alias with prepended TRASH_VOLUMES=$PWD.

**Comment by jvschiavo** [comment]
> Yes, --trash-dirs do work with above mentioned workaround, prepend with TRASH_VOLUMES=$PWD, i.e.:
> 
> TRASH_VOLUMES=$PWD trash-list --trash-dirs
> 
> Unfortunately, it works for everything except for trash-restore.
> 
> For everything else, create alias with prepended TRASH_VOLUMES=$PWD.

I'm sorry, I was tired at the moment and didn't pay enough attention to the previous comments. It does work indeed, thanks.

**Comment by robertkirkman** [comment]
I'm making an update to `pkg install python-psutil` here that will fix this

- https://github.com/termux/termux-packages/pull/28877
