### ISSUE TITLE
trash remove non existing files on a mounted windows share, trash process hangs

### ISSUE THREAD

**Issue by nenads79** [andreafrancia/trash-cli#58]
Hi,
I noticed something:
When using trash command on a linux local partition in some directory:
## trash non existent file extensions:

like: trash *.obj
## I get: trash: cannot trash non existent `*.obj'

But doing this on a mounted share (samba) used cifs mount command for a windows share.
If even one file exists everything is ok if I do try to trashing non existing files 
like: trash *.obj  
this hangs - I have to do a keyboard interrupt 
^CTraceback (most recent call last):
  File "/opt/anaconda2.3.0/bin/trash", line 4, in <module>
    **import**('pkg_resources').run_script('trash-cli==0.12.9.14.post0', 'trash')
  File "/opt/anaconda2.3.0/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/**init**.py", line 735, in run_script
  File "/opt/anaconda2.3.0/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/**init**.py", line 1659, in run_script
  File "/opt/anaconda2.3.0/lib/python2.7/site-packages/trash_cli-0.12.9.14.post0-py2.7.egg/EGG-INFO/scripts/trash", line 5, in <module>

  File "build/bdist.linux-x86_64/egg/trashcli/cmds.py", line 10, in put
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 548, in run
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 557, in trash_all
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 560, in trash
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 324, in trash
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 71, in trash
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 191, in persist_trash_info
KeyboardInterrupt

I replicated this issue on two different environments with permanent mounts. Same thing every time.
Also tried it with versions trash 0.12.9.14 and 0.12.7 on Ubuntu1404 x64
Best

**Comment by roth-a** [comment]
I have the same issue.....

**Comment by arthursw** [comment]
Note: I had problems with trash-list, trash-empty and trash-restore, they would hang and do nothing because of a problem with my mounted volumes. I unmounted all my volumes, and trash-cli worked again.

**Comment by andreafrancia** [comment]
@nenads79 this is a know bug of very old version of trash-cli.
Should be solved now.
