### ISSUE TITLE
Integration test fails

### ISSUE THREAD

**Issue by ari3s** [andreafrancia/trash-cli#61]
I prepared the development environment in Fedora 22 according to the documentation. The unit test passes, but the integration test fails:

```
(env)[jberan@dhcp-24-186 trash-cli2]$ nosetests integration_tests
.F.......SS......................................................................
======================================================================
FAIL: integration_tests.describe_trash_list.describe_trash_list.should_output_info_for_multiple_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jberan/git/trash-cli2/env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jberan/git/trash-cli2/integration_tests/describe_trash_list.py", line 76, in should_output_info_for_multiple_files
    self.user.should_read_output( "2000-01-01 00:00:01 /file1\n"
  File "/home/jberan/git/trash-cli2/integration_tests/describe_trash_list.py", line 296, in should_read_output
    self.stdout.assert_equal_to(expected_value)
  File "/home/jberan/git/trash-cli2/integration_tests/output_collector.py", line 11, in assert_equal_to
    return self.should_be(expected)
  File "/home/jberan/git/trash-cli2/integration_tests/output_collector.py", line 13, in should_be
    assert_equals_with_unidiff(expected, self.stream.getvalue())
  File "/home/jberan/git/trash-cli2/integration_tests/assert_equals_with_unidiff.py", line 19, in assert_equals_with_unidiff
    unidiff(expected, actual))
AssertionError: 
Expected:'2000-01-01 00:00:01 /file1\n2000-01-01 00:00:02 /file2\n2000-01-01 00:00:03 /file3\n'
  Actual:'2000-01-01 00:00:03 /file3\n2000-01-01 00:00:02 /file2\n2000-01-01 00:00:01 /file1\n'
--- Expected
+++ Actual
@@ -1,3 +1,3 @@
+2000-01-01 00:00:03 /file3
+2000-01-01 00:00:02 /file2
 2000-01-01 00:00:01 /file1
-2000-01-01 00:00:02 /file2
-2000-01-01 00:00:03 /file3


----------------------------------------------------------------------
Ran 81 tests in 0.282s

FAILED (SKIP=2, failures=1)

```

**Comment by andreafrancia** [comment]
Works on my Mac OS X.

**Comment by andreafrancia** [comment]
Let's try on a Linux Box...

**Comment by andreafrancia** [comment]
The problem is that it works on my machine (a Mac OS X) ad I don't have (yet) any Fedora or Ubuntu machine to test it. I don't know whether this problem it happen only on your machine or not and I haven't a Linux machine to test the code. I've updated the todo list in (TODO.txt) adding the steps to solve these problems.

**Comment by andreafrancia** [comment]
OK, found, the problem happen also on a Ubuntu Linux Box, it seems that it depends from the order of the line of output and it seems that there is a bunch of code to be untangled before fixing it.
