### ISSUE TITLE
trash-empty => OSError: [Errno 22] Invalid argument: '/home/elijah/.local/share/Trash/files/.'

### ISSUE THREAD

**Issue by ElijahLynn** [andreafrancia/trash-cli#64]
```
$ trash-empty
Traceback (most recent call last):
  File "/usr/local/bin/trash-empty", line 5, in <module>
    pkg_resources.run_script('trash-cli==0.12.9.14-r0', 'trash-empty')
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 517, in run_script
    for ep in entries.values():
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1443, in run_script
    path = self.module_path
  File "/usr/local/lib/python2.7/dist-packages/trash_cli-0.12.9.14_r0-py2.7.egg/EGG-INFO/scr
ipts/trash-empty", line 5, in <module>
    pkg_resources.run_script('trash-cli==0.12.9.14-r0', 'trash-empty')
  File "build/bdist.linux-x86_64/egg/trashcli/cmds.py", line 31, in empty
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 937, in run
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 806, in __call__
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 963, in _empty_all_trashdirs
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 879, in list_trashdirs
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 884, in emit_home_trashcan
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 238, in path_to
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 883, in return_result_with_vol
ume
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 978, in _analize_trash_directo
ry
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 1087, in each_trashinfo
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 856, in delete_if_expired
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 866, in _delete_unconditionall
y
  File "build/bdist.linux-x86_64/egg/trashcli/trash.py", line 839, in delete_trashinfo_and_b
ackup_copy
  File "build/bdist.linux-x86_64/egg/trashcli/fs.py", line 27, in remove_file_if_exists
  File "build/bdist.linux-x86_64/egg/trashcli/fs.py", line 25, in remove_file
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 22] Invalid argument: '/home/elijah/.local/share/Trash/files/.'
```

**Comment by ElijahLynn** [comment]
lol, just came across this issue again today and found my own post. Hopefully I figure it out soon!

**Comment by ElijahLynn** [comment]
K, so I deleted /home/elijah/.local/share/Trash/files/ manually and then tested again and that resolved the issue.

**Comment by andreafrancia** [comment]
Ok, if you think you have solved I'm going to close the issue. If you have problem reopen it.
