### ISSUE TITLE
trash-rm crashes on .trashinfo files without Path

### ISSUE THREAD

**Issue by simonbcn** [andreafrancia/trash-cli#69]
Arch Linux 64 bits
`trash-cli` installed from Arch repositories

```
$ trash-rm '*.jpg'
Traceback (most recent call last):
  File "/usr/bin/trash-rm", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/trashcli/rm.py", line 45, in main
    main.run(sys.argv)
  File "/usr/lib/python2.7/site-packages/trashcli/rm.py", line 35, in run
    trashdirs.list_trashdirs()
  File "/usr/lib/python2.7/site-packages/trashcli/trash.py", line 389, in list_trashdirs
    self._for_each_volume_trashcan()
  File "/usr/lib/python2.7/site-packages/trashcli/trash.py", line 396, in _for_each_volume_trashcan
    self.emit_trashcans_for(volume)
  File "/usr/lib/python2.7/site-packages/trashcli/trash.py", line 399, in emit_trashcans_for
    self.emit_trashcan_2_for(volume)
  File "/usr/lib/python2.7/site-packages/trashcli/trash.py", line 412, in emit_trashcan_2_for
    self.on_trash_dir_found(alt_top_trashdir, volume)
  File "/usr/lib/python2.7/site-packages/trashcli/rm.py", line 68, in list_from_volume_trashdir
    self.trashdir.each_trashinfo(self._report_original_location)
  File "/usr/lib/python2.7/site-packages/trashcli/trash.py", line 573, in each_trashinfo
    action(os.path.join(self._info_dir(), entry))
  File "/usr/lib/python2.7/site-packages/trashcli/rm.py", line 72, in _report_original_location
    path = parse_path(trashinfo)
  File "/usr/lib/python2.7/site-packages/trashcli/trash.py", line 650, in parse_path
    raise ParseError('Unable to parse Path')
trashcli.trash.ParseError: Unable to parse Path
```

**Comment by protist** [comment]
It crashes because you are single-quoting the glob. `'*.jpg'` won't expand. Test it with
```
$ ls '*.jpg'
$ ls *.jpg
```
The error message even suggests this: `Unable to parse Path`.

**Comment by simonbcn** [comment]
In the man file of `trash-rm` there are 2 examples, one of them is:
```
....
$ trash-rm '*.c'    # Removes all files ending with '.o' in trash can
....
```

I don't want expand the glob in present folder. The `ls` command isn't the same that a python utility like this.

In any case, it fails too with `trash-rm *.jpg` and `trash-rm "*.jpg"`.

**Comment by protist** [comment]
Oops, sorry, I totally misread it. Hopefully the developer responds, but I suspect that trash-cli has been abandoned, given the list of issues that haven't been replied to.
