### ISSUE TITLE
trash-empty (n) not working

### ISSUE THREAD

**Issue by kazakore** [andreafrancia/trash-cli#71]
I have been using the trash-empty part of trash-cli for some time, usually in the format trash-empty 30. Today I am running into the below errors when I try the command. System is Ubuntu Studio 16.04, with some changes to default, but as I say it always worked previous.

> ~$ trash-empty 30
> Traceback (most recent call last):
>   File "/usr/bin/trash-empty", line 5, in <module>
>     sys.exit(main())
>   File "/usr/lib/python2.7/dist-packages/trashcli/cmds.py", line 31, in empty
>     ).run(*sys.argv)
>   File "/usr/lib/python2.7/dist-packages/trashcli/trash.py", line 937, in run
>     parse(argv)
>   File "/usr/lib/python2.7/dist-packages/trashcli/trash.py", line 806, in __call__
>     self.default_action()
>   File "/usr/lib/python2.7/dist-packages/trashcli/trash.py", line 963, in _empty_all_trashdirs
>     self.trashdirs.list_trashdirs()
>   File "/usr/lib/python2.7/dist-packages/trashcli/trash.py", line 880, in list_trashdirs
>     self._for_each_volume_trashcan()
>   File "/usr/lib/python2.7/dist-packages/trashcli/trash.py", line 887, in _for_each_volume_trashcan
>     self.emit_trashcans_for(volume)
>   File "/usr/lib/python2.7/dist-packages/trashcli/trash.py", line 890, in emit_trashcans_for
>     self.emit_trashcan_2_for(volume)
>   File "/usr/lib/python2.7/dist-packages/trashcli/trash.py", line 903, in emit_trashcan_2_for
>     self.on_trash_dir_found(alt_top_trashdir, volume)
>   File "/usr/lib/python2.7/dist-packages/trashcli/trash.py", line 978, in _analize_trash_directory
>     self.trashdir.each_trashinfo(self.on_trashinfo_found)
>   File "/usr/lib/python2.7/dist-packages/trashcli/trash.py", line 1087, in each_trashinfo
>     action(os.path.join(self._info_dir(), entry))
>   File "/usr/lib/python2.7/dist-packages/trashcli/trash.py", line 856, in delete_if_expired
>     self._maybe_delete(trashinfo_path)
>   File "/usr/lib/python2.7/dist-packages/trashcli/trash.py", line 864, in _delete_according_date
>     )(contents)
>   File "/usr/lib/python2.7/dist-packages/trashcli/trash.py", line 1173, in __call__
>     self.found_deletion_date(date)
>   File "/usr/lib/python2.7/dist-packages/trashcli/trash.py", line 987, in __call__
>     self.then()
>   File "/usr/lib/python2.7/dist-packages/trashcli/trash.py", line 862, in <lambda>
>     lambda: self._delete_unconditionally(trashinfo_path)
>   File "/usr/lib/python2.7/dist-packages/trashcli/trash.py", line 866, in _delete_unconditionally
>     self._trashcan.delete_trashinfo_and_backup_copy(trashinfo_path)
>   File "/usr/lib/python2.7/dist-packages/trashcli/trash.py", line 839, in delete_trashinfo_and_backup_copy
>     self._file_remover.remove_file_if_exists(backup_copy)
>   File "/usr/lib/python2.7/dist-packages/trashcli/fs.py", line 27, in remove_file_if_exists
>     if os.path.exists(path): self.remove_file(path)
>   File "/usr/lib/python2.7/dist-packages/trashcli/fs.py", line 25, in remove_file
>     shutil.rmtree(path)
>   File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
>     rmtree(fullname, ignore_errors, onerror)
>   File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
>     onerror(os.remove, fullname, sys.exc_info())
>   File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
>     os.remove(fullname)
> OSError: [Errno 13] Permission denied: '/media/xxxx/Data/.Trash-1000/files/Pornophonik - Rubycurve [P36-011] (2)/Rubycurve/7TheEndOfRubycurveRubycurvePart3.ogg'
>

**Comment by kazakore** [comment]
Something strange with the files in the mentioned OSError. Deleted manually from recycle bin and tool runs as normal.
